### ISSUE TITLE
Applicable to text sequence labeling?

### ISSUE THREAD

**Issue by bratao** [satyajitneogiju/FLDCRF-for-sequence-labeling#1]
Think you for the code release @satyajitneogiju . Impressive paper!

Do you think that this algorithm is applicable to text sequence labeling tasks such as Named Entity Recognition?

**Comment by satyajitneogiju** [comment]
Yes. For sure. Perhaps you may want to extend the feature functions, or add 2nd, 3rd order Markov links to capture long range dependencies. But, try out the simpler versions applied in the paper/codes first. They may just be enough. 

Also, try increasing hidden layers/states for large datasets, depending on performance. If the system does not have enough RAM, you may need to write some GPU functions. I wrote some Python codes in this line, may share if interested.

**Comment by satyajitneogiju** [comment]
Also, you could see the LSTM performance on test data, going through the validation process. I am not sure if papers reporting LSTM performance are doing it, they may just be sharing the best performance on test data.
